
curl  --compressed --output Runny.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Runny.dll
curl  --compressed --output mscorlib.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/mscorlib.dll
curl  --compressed --output System.Net.Http.Json.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Net.Http.Json.dll
curl  --compressed --output System.Buffers.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Buffers.dll
curl  --compressed --output System.Threading.Tasks.Extensions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Threading.Tasks.Extensions.dll
curl  --compressed --output System.Text.Json.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Text.Json.dll
curl  --compressed --output System.Memory.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Memory.dll
curl  --compressed --output System.Runtime.CompilerServices.Unsafe.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Runtime.CompilerServices.Unsafe.dll
curl  --compressed --output Microsoft.Bcl.AsyncInterfaces.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Bcl.AsyncInterfaces.dll
curl  --compressed --output netstandard.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/netstandard.dll
curl  --compressed --output System.Xml.Linq.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Xml.Linq.dll
curl  --compressed --output System.Core.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Core.dll
curl  --compressed --output System.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.dll
curl  --compressed --output WebAssembly.Net.WebSockets.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/WebAssembly.Net.WebSockets.dll
curl  --compressed --output WebAssembly.Bindings.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/WebAssembly.Bindings.dll
curl  --compressed --output System.Numerics.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Numerics.dll
curl  --compressed --output System.Xml.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Xml.dll
curl  --compressed --output Mono.Security.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Mono.Security.dll
curl  --compressed --output System.Transactions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Transactions.dll
curl  --compressed --output System.Runtime.Serialization.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Runtime.Serialization.dll
curl  --compressed --output System.ServiceModel.Internals.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.ServiceModel.Internals.dll
curl  --compressed --output System.Net.Http.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Net.Http.dll
curl  --compressed --output System.Net.Http.WebAssemblyHttpHandler.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Net.Http.WebAssemblyHttpHandler.dll
curl  --compressed --output System.ComponentModel.Composition.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.ComponentModel.Composition.dll
curl  --compressed --output System.IO.Compression.FileSystem.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.IO.Compression.FileSystem.dll
curl  --compressed --output System.IO.Compression.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.IO.Compression.dll
curl  --compressed --output System.Drawing.Common.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Drawing.Common.dll
curl  --compressed --output System.Data.DataSetExtensions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Data.DataSetExtensions.dll
curl  --compressed --output System.Data.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Data.dll
curl  --compressed --output System.Numerics.Vectors.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Numerics.Vectors.dll
curl  --compressed --output System.Text.Encodings.Web.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Text.Encodings.Web.dll
curl  --compressed --output Microsoft.Extensions.DependencyInjection.Abstractions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.DependencyInjection.Abstractions.dll
curl  --compressed --output Microsoft.AspNetCore.Components.Web.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.AspNetCore.Components.Web.dll
curl  --compressed --output Microsoft.AspNetCore.Components.Forms.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.AspNetCore.Components.Forms.dll
curl  --compressed --output System.ComponentModel.Annotations.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.ComponentModel.Annotations.dll
curl  --compressed --output System.ComponentModel.DataAnnotations.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.ComponentModel.DataAnnotations.dll
curl  --compressed --output Microsoft.AspNetCore.Components.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.AspNetCore.Components.dll
curl  --compressed --output Microsoft.Extensions.Logging.Abstractions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Logging.Abstractions.dll
curl  --compressed --output Microsoft.AspNetCore.Components.WebAssembly.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.AspNetCore.Components.WebAssembly.dll
curl  --compressed --output Microsoft.Extensions.DependencyInjection.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.DependencyInjection.dll
curl  --compressed --output Microsoft.Extensions.Primitives.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Primitives.dll
curl  --compressed --output Microsoft.Extensions.Configuration.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Configuration.dll
curl  --compressed --output Microsoft.Extensions.Configuration.Abstractions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Configuration.Abstractions.dll
curl  --compressed --output Microsoft.Extensions.Configuration.Json.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Configuration.Json.dll
curl  --compressed --output Microsoft.Extensions.Configuration.FileExtensions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Configuration.FileExtensions.dll
curl  --compressed --output Microsoft.Extensions.FileProviders.Physical.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.FileProviders.Physical.dll
curl  --compressed --output Microsoft.Extensions.FileSystemGlobbing.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.FileSystemGlobbing.dll
curl  --compressed --output Microsoft.Extensions.FileProviders.Abstractions.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.FileProviders.Abstractions.dll
curl  --compressed --output Microsoft.Extensions.Logging.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Logging.dll
curl  --compressed --output Microsoft.Extensions.Options.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.Extensions.Options.dll
curl  --compressed --output Microsoft.JSInterop.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.JSInterop.dll
curl  --compressed --output Microsoft.JSInterop.WebAssembly.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.JSInterop.WebAssembly.dll
curl  --compressed --output System.Collections.Immutable.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Collections.Immutable.dll
curl  --compressed --output Microsoft.CodeAnalysis.CSharp.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.CodeAnalysis.CSharp.dll
curl  --compressed --output System.Reflection.Metadata.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Reflection.Metadata.dll
curl  --compressed --output Microsoft.CodeAnalysis.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/Microsoft.CodeAnalysis.dll
curl  --compressed --output System.Text.Encoding.CodePages.dll -L https://runny.z6.web.core.windows.net/_framework/_bin/System.Text.Encoding.CodePages.dll

